services: 
  backend: 
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: ["sh", "-c", "npm install && npm run start"]
    environment:
      POSTGRES_PASSWORD: password
      CLIENT_ID: 1231231231
      CLIENT_SECRET: 234234234
      DATABASE_URL: postgresql://user:password@database/mydb
  frontend: 
    image: node:18-alpine
    ports:
      - "3001:3001"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: ["sh", "-c", "npm install && npm run dev"]
  database:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
