name: Deploy Backend to AWS ECS

on:
  push:
    branches:
      - main  # o la rama principal de tu repo
    paths-ignore: 
      - 'frontend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev

    env:
      AWS_REGION: ${{ vars.AWS_REGION }}
      ECR_REGISTRY: 127214178414.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com
      ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
      IMAGE_TAG: latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

      - name: Build and push Docker image to ECR
        run: |
          docker buildx build --platform linux/amd64 --push \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./backend

      - name: Force ECS redeploy
        run: |
          aws ecs update-service \
            --cluster ${{ vars.ECS_CLUSTER }} \
            --service ${{ vars.ECS_SERVICE }} \
            --force-new-deployment \
            --region $AWS_REGION